version: '3.9'
services:
  postgres:
    image: postgres:14
    container_name: pfm-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pfm
    volumes:
      - pfm_pgdata:/var/lib/postgresql/data

volumes:
  pfm_pgdata: